mysql:
  username: root
  password: 123456
  host: 127.0.0.1
  port: 3306
  database: go_chat
  charset: utf8mb4
  dns: root:123456@tcp(127.0.0.1:3306)/go_chat?charset=utf8mb4&parseTime=True&loc=Local