definitions:
  models.CreateUserAttributes:
    properties:
      name:
        type: string
      password:
        type: string
      passwordConfirmation:
        type: string
    type: object
info:
  contact: {}
paths:
  /index:
    get:
      responses:
        "200":
          description: OK
          schema:
            type: string
      tags:
      - 首页
  /user/{id}:
    delete:
      parameters:
      - description: User ID
        format: int64
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: code", "users"}
          schema:
            type: string
      summary: 删除用户
      tags:
      - 用户模块
    patch:
      parameters:
      - description: User ID
        format: int64
        in: path
        name: id
        required: true
        type: integer
      - description: 用户
        in: body
        name: User
        required: true
        schema:
          $ref: '#/definitions/models.CreateUserAttributes'
      responses:
        "200":
          description: code", "users"}
          schema:
            type: string
      summary: 编辑用户
      tags:
      - 用户模块
  /users:
    get:
      responses:
        "200":
          description: code", "users"}
          schema:
            type: string
      summary: 用户列表
      tags:
      - 用户模块
    post:
      parameters:
      - description: 用户
        in: body
        name: User
        required: true
        schema:
          $ref: '#/definitions/models.CreateUserAttributes'
      responses:
        "200":
          description: code", "users"}
          schema:
            type: string
      summary: 新增用户
      tags:
      - 用户模块
swagger: "2.0"
